security:
  providers:
    app_user_provider:
      entity:
        class: App\Domain\Entity\MealPlanning\User
        property: id

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Application\Security\NoPasswordAuthenticator
      remember_me:
        secret: '%env(APP_SECRET)%'       # Make sure to set this in your .env file
        lifetime: 2592000                 # 30 days in seconds (30 * 24 * 60 * 60)
        path: /                           # Make the cookie available site-wide
        always_remember_me: true          # Automatically remember the user without checking a checkbox
      logout:
        path: app_logout
        invalidate_session: true
        target: /login
