version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
    ports:
      - "80:8000"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  postgres_data:
